// <auto-generated />
namespace Jeton.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Jeton_Mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Jeton_Mig));
        
        string IMigrationMetadata.Id
        {
            get { return "201611111048376_Jeton_Mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
